// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLastOrganizationState() {
  return window['go']['app']['App']['GetLastOrganizationState']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function OrganizeFiles(arg1, arg2) {
  return window['go']['app']['App']['OrganizeFiles'](arg1, arg2);
}

export function ResolveDroppedPath(arg1) {
  return window['go']['app']['App']['ResolveDroppedPath'](arg1);
}

export function SelectDestinationFolder() {
  return window['go']['app']['App']['SelectDestinationFolder']();
}

export function SelectSourceFolder() {
  return window['go']['app']['App']['SelectSourceFolder']();
}

export function SetCriterion(arg1, arg2) {
  return window['go']['app']['App']['SetCriterion'](arg1, arg2);
}

export function SetLanguage(arg1) {
  return window['go']['app']['App']['SetLanguage'](arg1);
}

export function UndoLastOrganization() {
  return window['go']['app']['App']['UndoLastOrganization']();
}
