// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {settings} from '../models';
import {organizer} from '../models';
import {undo} from '../models';

export function GetLastOrganizationState():Promise<app.OrganizationState>;

export function GetSettings():Promise<settings.View>;

export function OrganizeFiles(arg1:string,arg2:string):Promise<organizer.Result>;

export function ResolveDroppedPath(arg1:string):Promise<app.DroppedPath>;

export function SelectDestinationFolder():Promise<string>;

export function SelectSourceFolder():Promise<string>;

export function SetCriterion(arg1:string,arg2:boolean):Promise<settings.View>;

export function SetLanguage(arg1:string):Promise<settings.View>;

export function UndoLastOrganization():Promise<undo.Result>;
