// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['app']['App']['Cancel']();
}

export function ClearNotifications() {
  return window['go']['app']['App']['ClearNotifications']();
}

export function DropPaths(arg1) {
  return window['go']['app']['App']['DropPaths'](arg1);
}

export function GetState() {
  return window['go']['app']['App']['GetState']();
}

export function MarkNotificationsRead() {
  return window['go']['app']['App']['MarkNotificationsRead']();
}

export function OpenDestination() {
  return window['go']['app']['App']['OpenDestination']();
}

export function Organize() {
  return window['go']['app']['App']['Organize']();
}

export function SelectDestination() {
  return window['go']['app']['App']['SelectDestination']();
}

export function SelectSource() {
  return window['go']['app']['App']['SelectSource']();
}

export function SetCriterion(arg1, arg2) {
  return window['go']['app']['App']['SetCriterion'](arg1, arg2);
}

export function SetDuplicates(arg1) {
  return window['go']['app']['App']['SetDuplicates'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['app']['App']['SetLanguage'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['app']['App']['SetTheme'](arg1);
}

export function StartOver() {
  return window['go']['app']['App']['StartOver']();
}

export function Undo() {
  return window['go']['app']['App']['Undo']();
}
