// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function Cancel():Promise<app.ViewState>;

export function ClearNotifications():Promise<app.ViewState>;

export function DropPaths(arg1:Array<string>):Promise<app.ViewState>;

export function GetState():Promise<app.ViewState>;

export function MarkNotificationsRead():Promise<app.ViewState>;

export function Organize():Promise<app.ViewState>;

export function SelectDestination():Promise<app.ViewState>;

export function SelectSource():Promise<app.ViewState>;

export function SetCriterion(arg1:string,arg2:boolean):Promise<app.ViewState>;

export function SetLanguage(arg1:string):Promise<app.ViewState>;

export function SetTheme(arg1:string):Promise<app.ViewState>;

export function Undo():Promise<app.ViewState>;
